//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DP.Chess.MAUI.Resources.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DP.Chess.MAUI.Resources.I18N.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current player.
        /// </summary>
        internal static string Chess_CurrentPlayer_Label {
            get {
                return ResourceManager.GetString("Chess_CurrentPlayer_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chess.
        /// </summary>
        internal static string Chess_Label {
            get {
                return ResourceManager.GetString("Chess_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the opponent&apos;s king.
        /// </summary>
        internal static string Chess_WinningCondition_Description {
            get {
                return ResourceManager.GetString("Chess_WinningCondition_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winning condition.
        /// </summary>
        internal static string Chess_WinningCondition_Label {
            get {
                return ResourceManager.GetString("Chess_WinningCondition_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to win the game, the king has to be taken.  The game will not indicate a check or checkmate condition..
        /// </summary>
        internal static string Chess_WinningCondition_ToolTip {
            get {
                return ResourceManager.GetString("Chess_WinningCondition_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading the save file!.
        /// </summary>
        internal static string General_GameLoaded_Error {
            get {
                return ResourceManager.GetString("General_GameLoaded_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game loaded successfully!.
        /// </summary>
        internal static string General_GameLoaded_Success {
            get {
                return ResourceManager.GetString("General_GameLoaded_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more movement redos possible..
        /// </summary>
        internal static string General_GameRedo_Error {
            get {
                return ResourceManager.GetString("General_GameRedo_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving the game!.
        /// </summary>
        internal static string General_GameSaved_Error {
            get {
                return ResourceManager.GetString("General_GameSaved_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game saved successfully!.
        /// </summary>
        internal static string General_GameSaved_Success {
            get {
                return ResourceManager.GetString("General_GameSaved_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more movement undos possible..
        /// </summary>
        internal static string General_GameUndo_Error {
            get {
                return ResourceManager.GetString("General_GameUndo_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid move.
        /// </summary>
        internal static string General_InvalidMove_Label {
            get {
                return ResourceManager.GetString("General_InvalidMove_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string General_Load_Label {
            get {
                return ResourceManager.GetString("General_Load_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string General_Redo_Label {
            get {
                return ResourceManager.GetString("General_Redo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a new game.
        /// </summary>
        internal static string General_Restart_Description {
            get {
                return ResourceManager.GetString("General_Restart_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        internal static string General_Restart_Label {
            get {
                return ResourceManager.GetString("General_Restart_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string General_Save_Label {
            get {
                return ResourceManager.GetString("General_Save_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string General_Undo_Label {
            get {
                return ResourceManager.GetString("General_Undo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner: {0}!.
        /// </summary>
        internal static string General_Winner_Label {
            get {
                return ResourceManager.GetString("General_Winner_Label", resourceCulture);
            }
        }
    }
}
